.TH NetworkDesigner 1 "September, 2014" Linux "User Manual"
.SH NAME:
NetworkDesigner \- An impedance matching network designer
.SH SYNOPSIS:
.B NetworkDesigner [\-v \--version]
.SH DESCRIPTION:
.B NetworkDesigner
is a graphical design aid for the design of impedance matching networks. There
are nine of the most common topologies available for both solid state and
vacuum tube designs.
.P
The project results are displayed in the main window, and may be saved to disk
and/or printed out. 
.P
.I See the on-line help for further information.
NetworkDesigner comes with detailed help documentation that is available
from either the toolbar or the main menu.
.SH OPTIONS:
.TP
\-v \--version: Show the version of the app on standard output, then exit.
.SH DIAGNOSTICS:
.B NetworkDesigner 
includes various message boxes and interactive dialogs to alert the
user to correctable, non-fatal errors. Other dialogs query for
confirmation before performing any action that could lose data. There
are also diagnostics printed to standard output that are viewable when starting
the app from a command line. These are mainly for debugging/developer maintenance.
.SH AUTHOR:
.B NetworkDesigner
was written by Simo. Developed with
the
.I FOX Toolkit
(http://www.fox-toolkit.org), and
.I XEMACS
(http://www.xemacs.org). Also debugged with 
.I Data Display Debugger
.SH REPORT BUGS:
Send bug reports to: simo@furrydolphin.net
.SH COPYRIGHT:
.B NetworkDesigner
is Copyright (C) 2013 by Simo. This program is free software.
See the on-line help for text of the GNU Public License.
