/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file CancelX.gif */
extern const unsigned char CancelX_gif[];

/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file Exit.gif */
extern const unsigned char Exit_gif[];

/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file LedGray.gif */
extern const unsigned char LedGray_gif[];

/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file LedOff.gif */
extern const unsigned char LedOff_gif[];

/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file LedOn.gif */
extern const unsigned char LedOn_gif[];

/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file New.gif */
extern const unsigned char New_gif[];

/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file OKCheck.gif */
extern const unsigned char OKCheck_gif[];

/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file about.gif */
extern const unsigned char about_gif[];

/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file atl-dolphin.gif */
extern const unsigned char atldolphin_gif[];

/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file clear_up.gif */
extern const unsigned char clear_up_gif[];

/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file copy.gif */
extern const unsigned char copy_gif[];

/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file cut.gif */
extern const unsigned char cut_gif[];

/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file fileprint.gif */
extern const unsigned char fileprint_gif[];

/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file filesaveas.gif */
extern const unsigned char filesaveas_gif[];

/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file help.gif */
extern const unsigned char help_gif[];

/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file paste.gif */
extern const unsigned char paste_gif[];

